#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# config/routes.yaml

# the "app_lucky_number" route name is not important yet

login:
  path: /
  controller: App\Controller\SecurityController::index
