#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# config/routes.yaml

login:
  path: /login
  controller: App\Controller\SecurityController::login

app_homepage:
  path: /
  controller: App\Controller\HomeController::index

app_logout:
    path: /logout

app_calendarConges:
  path: /mesConges
  controller: App\Controller\CalendarCongesController::index

app_noteFrais:
  path: /mesNotesDeFrais
  controller: App\Controller\NoteFraisController::index

app_gestionNotesFrais:
  path: /gestionNotesFrais
  controller: App\Controller\GestionNotesFraisController::index

app_demandesDeConges:
  path: /mesDemandesDeConges
  controller: App\Controller\GestionNotesFraisController::index

app_gestionDemandesDeConges:
  path: /gestionDemandesDeConges
  controller: App\Controller\GestionNotesFraisController::index

app_demandesDInformation:
  path: /mesDemandesDInformation
  controller: App\Controller\GestionNotesFraisController::index

app_gestionDemandesDInformation:
  path: /gestionDemandesDInformation
  controller: App\Controller\GestionNotesFraisController::index

app_missions:
  path: /mesMissions
  controller: App\Controller\MissionsController::index

app_gestionMissions:
  path: /gestionMissions
  controller: App\Controller\GestionNotesFraisController::index


app_gestionDemandesAvance:
  path: /gestionDemandesAvance
  controller: App\Controller\GestionDemandesAvanceController::index

app_gestionNotesFraisAdmin:
  path: /gestionNotesFraisChef
  controller: App\Controller\GestionNotesAdminController::index

app_admin:
  path: /admin
  controller: App\Controller\Admin\AdminCollaborateurController::index

app_profile:
  path: /profile
  controller: App\Controller\ProfilePageController::index
