#index:
#    path: /
#    controller: App\Controller\DefaultController::index



# config/routes.yaml

login:
  path: /login
  controller: App\Controller\SecurityController::login

app_homepage:
  path: /
  controller: App\Controller\HomeController::index

app_logout:
    path: /logout

app_noteFrais:
  path: /mesNotesDeFrais
  controller: App\Controller\NoteFraisController::index

#app_noteFrais:
#  path: /profile
#  controller: App\Controller\profile::index

app_admin:
  path: /admin
  controller: App\Controller\Admin\AdminCollaborateurController::index

app_profile:
  path: /profile
  controller: App\Controller\ProfilePageController::index
